### ISSUE TITLE
Display Plotly outputs in Students Exam Performance Notebook

### ISSUE THREAD

**Issue by Anubhav-Goyal01** [Anubhav-Goyal01/ML-Projects#1]
Currently, plotly graphs are not visible in the student's exam performance notebook.  Check out the plotly documentation and try to fix this issue.

**Comment by SpyzzVVarun** [comment]
Hi Anubhav, what version of plotly is being used in your notebook?

**Comment by SpyzzVVarun** [comment]
My plotly version is 5.5.0 and the code seems to run fine for me

**Comment by Anubhav-Goyal01** [comment]
Hello @SpyzzVVarun, I have version 5.9.0, my code is doing fine on Kaggle but the plots are not showing up on GitHub

**Comment by SpyzzVVarun** [comment]
@Anubhav-Goyal01 I don't think this is a bug, it's just how github works. It wont be able to render these interactive plots.

**Comment by SpyzzVVarun** [comment]
![donut_plot](https://user-images.githubusercontent.com/95134445/193451521-cc881590-5fd8-4051-8077-4d9b531325c5.png)
![table_plot](https://user-images.githubusercontent.com/95134445/193451529-6b47fea8-f9ce-4f58-b4b9-ae3c814573bb.jpeg)
I can add these plots instead of the plotly ones @Anubhav-Goyal01

**Comment by Anubhav-Goyal01** [comment]
They look amazing @SpyzzVVarun, I have merged your PR, I don't think any more changes are required.
